"""Power spectra and the sampling-rate question.

*****
Low-frequency-floor convention from dysts
*****

PANDA is not scale-free in time. Every trajectory it was trained on was generated by 'dysts' at 4096 timesteps / 40 periods ~ 102 samples per
dominant period. Feeding it a trajectory sampled ten times more finely is as much a distribution shift as changing the system, so before any forecast
comparison we measure the Lorenz '96 dominant period and resample to match.

"the dominant period"
For a chaotic system this is not a well-defined quantity, and the estimator matters. 
'dysts' stores a precomputed per-system period obtained from a surrogate-significance test on the periodogram.
we cannot reproduce that exactly without its metadata. Two estimators are provided:
* "centroid" (default) : amplitude-weighted mean frequency over the significant part of the spectrum. 
    Validated against eight 'dysts' systems generated at a known 102.4 samples/period, it recovers 63--113 (median ~100).
* "peak" : the single largest spectral peak. Simpler, but far less stable: on the same eight systems it ranges over 51--195, because for broad-band chaos the largest peak can land on a harmonic.

Neither is exact, so sweep the sampling density and check whether conclusions move.
"""

from __future__ import annotations
import numpy as np

PANDA_POINTS_PER_PERIOD = 4096 / 40  # the density used throughout PANDA's training set

# dysts discards frequencies below (1 / halflen) * 10; without a floor like this
# the centroid is dragged down by the near-DC power of a long chaotic record.
_LOW_FREQUENCY_FLOOR_FACTOR = 10.0
_CENTROID_POWER_THRESHOLD = 0.1  # keep bins within one decade of the peak


def power_spectrum(traj: np.ndarray, dt: float, *, detrend: bool = True, window: bool = False) -> tuple[np.ndarray, np.ndarray]:
    """One-sided power spectrum of a time-first trajectory, averaged over channels.
    dt: Sampling interval.
    window: Apply a Blackman-Harris window first, as 'dysts' does. Reduces spectral leakage; off by default so the raw spectrum is available.

    freqs: Positive frequencies (DC excluded).
    power: Channel-averaged power at each frequency.
    """
    series = np.atleast_2d(traj.T) if traj.ndim > 1 else traj[None, :]
    if detrend:
        series = series - series.mean(axis=-1, keepdims=True)
    n_times = series.shape[-1]
    if window:
        from scipy.signal.windows import blackmanharris

        series = series * blackmanharris(n_times)
    spectrum = np.abs(np.fft.rfft(series, axis=-1)) ** 2
    freqs = np.fft.rfftfreq(n_times, d=dt)
    return freqs[1:], spectrum.mean(axis=0)[1:]


def dominant_period(traj: np.ndarray, dt: float, *, method: str = "centroid") -> float:
    """Characteristic period of a trajectory.

    "centroid" for the amplitude-weighted mean frequency (default,stable)
    "peak" for the largest spectral peak (simple, unstable)
    See the module docstring for the validation behind that ranking.
    """
    freqs, power = power_spectrum(traj, dt, window=True)

    n_times = traj.shape[0]
    floor = _LOW_FREQUENCY_FLOOR_FACTOR / (n_times // 2) / dt
    keep = freqs > floor
    if not keep.any():
        raise ValueError(f"trajectory of {n_times} samples is too short to resolve any frequency above the low-frequency floor {floor:g}")
    freqs, power = freqs[keep], power[keep]

    if method == "peak":
        return float(1.0 / freqs[int(np.argmax(power))])
    if method == "centroid":
        significant = power > _CENTROID_POWER_THRESHOLD * power.max()
        return float(1.0 / np.average(freqs[significant], weights=power[significant]))
    raise ValueError(f"unknown method {method!r}; expected 'centroid' or 'peak'")


def points_per_period(traj: np.ndarray, dt: float, **kwargs: str) -> float:
    """Current sampling density, in samples per dominant period."""
    return dominant_period(traj, dt, **kwargs) / dt  # type: ignore[arg-type]


def subsample_for_points_per_period(traj: np.ndarray,dt: float,target_points_per_period: float = PANDA_POINTS_PER_PERIOD,**kwargs: str,) -> tuple[np.ndarray, float, int]:
    """Decimate a trajectory towards a target sampling density.
    Uses plain striding, so the achievable density is quantised; use `resample_to_points_per_period` when you need it exact.
    """
    current = points_per_period(traj, dt, **kwargs)
    stride = max(1, int(round(current / target_points_per_period)))
    return traj[::stride], dt * stride, stride


def resample_to_points_per_period(traj: np.ndarray,dt: float,target_points_per_period: float = PANDA_POINTS_PER_PERIOD,**kwargs: str,) -> tuple[np.ndarray, float]:
    """Linearly interpolate a trajectory onto an exact target sampling density.
    Prefer this over striding when the required stride would be fractional, which it usually is, since the Lorenz '96 dominant period is not a tidy multiple of the integration step.
    """
    period = dominant_period(traj, dt, **kwargs)  # type: ignore[arg-type]
    new_dt = period / target_points_per_period
    old_times = np.arange(traj.shape[0]) * dt
    new_times = np.arange(0.0, old_times[-1], new_dt)

    if traj.ndim == 1:
        return np.interp(new_times, old_times, traj), new_dt
    resampled = np.stack([np.interp(new_times, old_times, traj[:, c]) for c in range(traj.shape[1])], axis=-1)
    return resampled, new_dt
